---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.7
    commands:
      - pip install -r requirements.txt
      - pip install pytest flake8
      - pytest
      - flake8
  - name: release-docker
    image: plugins/docker
    settings:
      username: jakewalker
      password:
        from_secret: docker_password
      repo: jakewalker/webssh
      tags: latest
